#!/usr/bin/env python3
"""Add all missing page entries to generate-seo-pages.cjs"""

with open('scripts/generate-seo-pages.cjs', 'r') as f:
    content = f.read()

# All new entries to insert
new_entries = '''  // === MISSING PAGES - Added to fix Google indexing crisis (65 pages) ===
  // Utility & Resource Pages
  "/administration-guide": { title: "Peptide Administration Guide", desc: "Comprehensive guide to peptide administration techniques for healthcare providers. Subcutaneous, intramuscular, intranasal, and oral delivery methods with step-by-step protocols.", type: "page" },
  "/ai-agent": { title: "Dr. Peptide AI Agent - Personalized Peptide Protocol Generator", desc: "Meet Dr. Peptide AI, your intelligent peptide protocol assistant. Generate personalized peptide therapy protocols using 16 specialized AI agents trained on 2,800+ clinical studies.", type: "page" },
  "/ai-faq": { title: "Dr. Peptide AI FAQ - Frequently Asked Questions", desc: "Frequently asked questions about Dr. Peptide AI. Learn how the AI generates personalized peptide protocols, data privacy, clinical accuracy, and more.", type: "page" },
  "/are-peptides-safe": { title: "Are Peptides Safe? Evidence-Based Safety Guide for Healthcare Providers", desc: "Comprehensive evidence-based guide on peptide safety for healthcare providers. Side effects, contraindications, monitoring protocols, and risk management for therapeutic peptides.", type: "page" },
  "/case-studies": { title: "Peptide Therapy Case Studies - Clinical Outcomes & Patient Results", desc: "Real-world peptide therapy case studies demonstrating clinical outcomes. Patient results, protocol details, and lessons learned for healthcare providers.", type: "page" },
  "/downloads": { title: "Peptide Therapy Downloads - E-Books, Guides & Clinical Resources", desc: "Free downloadable peptide therapy resources for healthcare providers. E-books, clinical guides, patient handouts, consent forms, and protocol templates.", type: "page" },
  "/embed": { title: "Embed Peptide Education Hub - Widget for Your Practice Website", desc: "Embed Peptide Education Hub content on your practice website. Peptide information widgets, dosing calculators, and educational resources for patient engagement.", type: "page" },
  "/glossary": { title: "Peptide Therapy Glossary - Key Terms & Definitions", desc: "Comprehensive glossary of peptide therapy terminology. Definitions for clinical terms, mechanisms of action, administration methods, and regulatory concepts.", type: "page" },
  "/infographics": { title: "Peptide Therapy Infographics - Visual Clinical Guides", desc: "Visual infographics for peptide therapy education. Mechanisms of action, dosing protocols, comparison charts, and clinical decision trees for healthcare providers.", type: "page" },
  "/insurance-billing": { title: "Peptide Therapy Insurance & Billing Guide", desc: "Navigate peptide therapy insurance billing and reimbursement. CPT codes, J-codes, prior authorization strategies, and billing best practices for healthcare providers.", type: "page" },
  "/patient-education": { title: "Patient Education Materials for Peptide Therapy", desc: "Patient-facing educational materials for peptide therapy. Handouts, FAQs, consent information, and administration guides to support patient understanding.", type: "page" },
  "/practice-toolkit": { title: "Peptide Practice Toolkit - Everything You Need to Start", desc: "Complete toolkit for starting a peptide therapy practice. Templates, protocols, compliance checklists, marketing materials, and business planning resources.", type: "page" },
  "/resources": { title: "Peptide Therapy Resources for Healthcare Providers", desc: "Curated collection of peptide therapy resources. Research databases, clinical guidelines, regulatory updates, supplier directories, and professional organizations.", type: "page" },
  "/safety-compliance": { title: "Peptide Therapy Safety & Compliance Guide", desc: "Comprehensive safety and compliance guide for peptide therapy practices. FDA regulations, state requirements, documentation standards, and quality assurance protocols.", type: "page" },
  "/safety-management": { title: "Peptide Safety Management - Risk Assessment & Monitoring", desc: "Safety management protocols for peptide therapy. Risk assessment frameworks, adverse event monitoring, patient safety checklists, and emergency procedures.", type: "page" },
  "/safety-standards": { title: "Peptide Quality & Safety Standards", desc: "Quality and safety standards for therapeutic peptides. USP guidelines, purity testing, potency verification, sterility requirements, and supplier qualification criteria.", type: "page" },
  "/stacking-guide": { title: "Peptide Stacking Guide - Combining Peptides Safely & Effectively", desc: "Evidence-based guide to peptide stacking for healthcare providers. Safe combinations, synergistic protocols, timing strategies, and contraindicated pairings.", type: "page" },
  "/statistics": { title: "Peptide Therapy Statistics & Market Data", desc: "Peptide therapy industry statistics, market data, and clinical outcomes. Growth trends, patient demographics, efficacy rates, and market projections.", type: "page" },
  "/supplier-directory": { title: "Peptide Supplier Directory - Verified 503A & 503B Pharmacies", desc: "Directory of verified peptide suppliers for healthcare providers. 503A compounding pharmacies, 503B outsourcing facilities, quality ratings, and ordering information.", type: "page" },
  "/video-library": { title: "Peptide Therapy Video Library - Educational Videos for Clinicians", desc: "Educational video library for peptide therapy. Clinical demonstrations, mechanism animations, expert interviews, and training modules for healthcare providers.", type: "page" },
  "/guides/ultimate-peptide-therapy-guide": { title: "The Ultimate Peptide Therapy Guide for Healthcare Providers", desc: "The most comprehensive peptide therapy guide available. From fundamentals to advanced protocols, everything healthcare providers need to master peptide therapy.", type: "page" },
  // Protocol Pages
  "/protocols/cognitive": { title: "Cognitive Enhancement Peptide Protocols", desc: "Evidence-based cognitive enhancement peptide protocols for healthcare providers. Nootropic stacks, neuroprotection regimens, and brain optimization strategies.", type: "page" },
  "/protocols/injury-healing": { title: "Injury Healing Peptide Protocols", desc: "Peptide protocols for accelerated injury healing and tissue repair. BPC-157, TB-500, and regenerative peptide combinations for clinical recovery.", type: "page" },
  "/protocols/longevity": { title: "Longevity & Anti-Aging Peptide Protocols", desc: "Anti-aging and longevity peptide protocols for healthcare providers. Telomere support, mitochondrial optimization, and cellular rejuvenation strategies.", type: "page" },
  "/protocols/metabolism": { title: "Metabolic Optimization Peptide Protocols", desc: "Metabolic optimization peptide protocols for healthcare providers. Fat loss, insulin sensitivity, and metabolic health improvement strategies.", type: "page" },
  "/protocols/weight-loss": { title: "Weight Loss Peptide Protocols - GLP-1, Tirzepatide & More", desc: "Evidence-based weight loss peptide protocols. Semaglutide, tirzepatide, and combination therapy protocols with dosing schedules and monitoring guidelines.", type: "page" },
  // Missing Peptide Pages
  "/peptides/glp-1": { title: "GLP-1 Receptor Agonists - Comprehensive Guide", desc: "Comprehensive guide to GLP-1 receptor agonist peptides for healthcare providers. Semaglutide, liraglutide, and emerging GLP-1 therapies with clinical protocols.", type: "peptide", category: "Weight Loss" },
  "/peptides/glutathione": { title: "Glutathione - Master Antioxidant Peptide", desc: "Comprehensive glutathione guide: master antioxidant mechanism, IV and oral dosing protocols, detoxification support, and clinical applications for healthcare providers.", type: "peptide", category: "Anti-Aging" },
  "/peptides/melanotan-1": { title: "Melanotan I (Afamelanotide) - Photoprotective Peptide", desc: "Comprehensive Melanotan I guide: alpha-MSH analog mechanism, photoprotection dosing, erythropoietic protoporphyria treatment, and clinical applications.", type: "peptide", category: "Skin" },
  "/peptides/nad": { title: "NAD+ Therapy - Nicotinamide Adenine Dinucleotide", desc: "Comprehensive NAD+ therapy guide: cellular energy mechanism, IV and subcutaneous protocols, anti-aging applications, and clinical dosing for healthcare providers.", type: "peptide", category: "Anti-Aging" },
  "/peptides/nad-nasal-spray": { title: "NAD+ Nasal Spray - Intranasal NAD+ Delivery", desc: "NAD+ nasal spray guide: intranasal delivery mechanism, bioavailability advantages, dosing protocols, and clinical applications for cognitive and anti-aging support.", type: "peptide", category: "Anti-Aging" },
  "/peptides/pinealon": { title: "Pinealon - Neuroprotective Tripeptide", desc: "Comprehensive Pinealon guide: EDR tripeptide mechanism, pineal gland support, neuroprotection dosing, circadian rhythm optimization, and clinical applications.", type: "peptide", category: "Cognitive Enhancement" },
  "/peptides/slu-pp-332": { title: "SLU-PP-332 - Exercise Mimetic ERR Agonist", desc: "Comprehensive SLU-PP-332 guide: ERR agonist mechanism, exercise mimetic effects, fat metabolism, muscle endurance enhancement, and clinical research.", type: "peptide", category: "Weight Loss" },
  "/peptides/bpc-157-capsules": { title: "BPC-157 Capsules - Oral BPC-157 Administration", desc: "BPC-157 oral capsule guide: oral bioavailability, gut healing protocols, dosing for GI applications, and comparison with injectable BPC-157.", type: "peptide", category: "Regenerative" },
  "/peptides/ghk-cu-serum": { title: "GHK-Cu Serum - Topical Copper Peptide", desc: "GHK-Cu serum guide: topical copper peptide application, skin rejuvenation protocols, wound healing, hair growth, and clinical dermatology applications.", type: "peptide", category: "Skin" },
  "/peptides/glow-blend-capsules": { title: "GLOW Capsules - Oral Beauty Supplement Blend", desc: "GLOW Capsules: oral beauty supplement peptide blend for skin health, collagen support, and anti-aging from within.", type: "formula", category: "Skin" },
  "/peptides/klow-blend-capsules": { title: "KLOW Capsules - Comprehensive Beauty From Within", desc: "KLOW Capsules: comprehensive beauty peptide blend for skin, hair, and nail health from within.", type: "formula", category: "Skin" },
  // === MISSING BLOG POSTS - All dynamic blog posts need pre-rendered HTML ===
  "/blog/getting-started": { title: "How to Start a Peptide Therapy Practice in 2026", desc: "A comprehensive guide for healthcare providers looking to integrate peptide therapy into their practice.", type: "article" },
  "/blog/choosing-supplier": { title: "How to Choose a Peptide Supplier: Quality Standards Guide", desc: "Essential guide for evaluating peptide suppliers including purity testing, COA verification, and regulatory compliance.", type: "article" },
  "/blog/bpc157-tb500": { title: "BPC-157 vs TB-500: Comparing Two Powerful Healing Peptides", desc: "Head-to-head comparison of BPC-157 and TB-500 for tissue repair, wound healing, and recovery applications.", type: "article" },
  "/blog/glp1-therapy": { title: "Semaglutide vs Tirzepatide: Complete GLP-1 Therapy Guide", desc: "Comprehensive comparison of semaglutide and tirzepatide for weight loss, including dosing protocols and clinical outcomes.", type: "article" },
  "/blog/quality-standards": { title: "Peptide Quality Standards: What Healthcare Providers Need to Know", desc: "Understanding peptide purity, potency, and quality testing standards for clinical applications.", type: "article" },
  "/blog/storage-handling": { title: "Peptide Storage and Handling: Best Practices Guide", desc: "Complete guide to proper peptide storage, handling, reconstitution, and stability for healthcare practices.", type: "article" },
  "/blog/practice-roi": { title: "Peptide Therapy ROI: Building a Profitable Practice", desc: "Financial analysis and business strategies for building a profitable peptide therapy practice.", type: "article" },
  "/blog/thymosin-alpha-1": { title: "Thymosin Alpha-1: Immune Modulation for Clinical Practice", desc: "Evidence-based guide to thymosin alpha-1 for immune support, cancer adjunct therapy, and chronic infections.", type: "article" },
  "/blog/pt-141": { title: "PT-141 (Bremelanotide): Sexual Wellness Applications", desc: "Clinical guide to PT-141 for sexual dysfunction in men and women, including dosing and patient selection.", type: "article" },
  "/blog/semax": { title: "Semax: Cognitive Enhancement and Neuroprotection", desc: "Comprehensive guide to semax for cognitive enhancement, stroke recovery, and neuroprotective applications.", type: "article" },
  "/blog/tesamorelin": { title: "Tesamorelin: Visceral Fat Reduction and GH Optimization", desc: "Clinical guide to tesamorelin for visceral fat reduction, lipodystrophy, and growth hormone optimization.", type: "article" },
  "/blog/melanotan-ii": { title: "Melanotan II: Photoprotection and Clinical Considerations", desc: "Evidence-based guide to Melanotan II for tanning, photoprotection, and sexual health applications.", type: "article" },
  "/blog/ipamorelin": { title: "Ipamorelin: Growth Hormone Secretagogue Guide", desc: "Comprehensive ipamorelin guide for GH optimization, anti-aging, and body composition improvement.", type: "article" },
  "/blog/ghk-cu": { title: "GHK-Cu: Regenerative Medicine and Skin Rejuvenation", desc: "Clinical guide to GHK-Cu copper peptide for wound healing, skin regeneration, and anti-aging applications.", type: "article" },
  "/blog/implementing-peptide-therapy": { title: "Implementing Peptide Therapy in Your Practice", desc: "Step-by-step implementation guide for adding peptide therapy services to your healthcare practice.", type: "article" },
  "/blog/peptideprotocols-ai": { title: "PeptideProtocols.AI: How AI is Revolutionizing Peptide Therapy", desc: "How Dr. Peptide AI uses 16 specialized agents to generate personalized peptide protocols from clinical data.", type: "article" },
  "/blog/founder-story": { title: "The Founder Story: Building Peptide Education Hub", desc: "The story behind Peptide Education Hub and the mission to democratize peptide therapy education.", type: "article" },
  "/blog/training-practitioners": { title: "Training Practitioners in Peptide Therapy", desc: "Guide to peptide therapy training programs, certifications, and continuing education for healthcare providers.", type: "article" },
  "/blog/dr-peptide-ai": { title: "Dr. Peptide AI: Your Intelligent Protocol Assistant", desc: "Introduction to Dr. Peptide AI and how it generates evidence-based peptide therapy protocols.", type: "article" },
  "/blog/neuro-series-formulas": { title: "Neuro Series Formulas: Advanced Cognitive Peptide Blends", desc: "Overview of the N-series cognitive enhancement formulas including N-69, N-111, N-259, N-2331, and N-5550.", type: "article" },
  "/blog/regen-metabolic-formulas": { title: "Regenerative and Metabolic Formulas: Advanced Peptide Blends", desc: "Overview of regenerative and metabolic peptide formulas including RG-5555, M-51, M-2531, and W-1175.", type: "article" },
  "/blog/ai-formula-design": { title: "AI-Driven Formula Design: The Future of Peptide Blends", desc: "How artificial intelligence is being used to design optimized peptide blend formulations.", type: "article" },
  "/blog/peptide-therapy-weight-loss": { title: "Peptide Therapy for Weight Loss: A Clinical Guide", desc: "Comprehensive guide to using peptides for weight loss including GLP-1 agonists, metabolic peptides, and combination protocols.", type: "article" },
  "/blog/anti-aging-peptides": { title: "Anti-Aging Peptides: Evidence-Based Longevity Protocols", desc: "Guide to anti-aging peptide therapies including epithalon, GHK-Cu, NAD+, and mitochondrial peptides.", type: "article" },
  "/blog/peptides-muscle-growth": { title: "Peptides for Muscle Growth and Body Composition", desc: "Evidence-based guide to peptides for muscle growth, recovery, and body composition optimization.", type: "article" },
  "/blog/peptides-injury-recovery": { title: "Peptides for Injury Recovery: Clinical Protocols", desc: "Clinical protocols for using BPC-157, TB-500, and regenerative peptides for accelerated injury recovery.", type: "article" },
  "/blog/peptides-cognitive-enhancement": { title: "Peptides for Cognitive Enhancement: Nootropic Guide", desc: "Guide to cognitive enhancement peptides including semax, selank, dihexa, and neuroprotective compounds.", type: "article" },
  "/blog/peptides-immune-support": { title: "Peptides for Immune Support: Clinical Applications", desc: "Evidence-based guide to immune-modulating peptides including thymosin alpha-1, LL-37, and KPV.", type: "article" },
  "/blog/peptides-sexual-health": { title: "Peptides for Sexual Health: PT-141 and Beyond", desc: "Clinical guide to peptides for sexual health including PT-141, kisspeptin, and oxytocin protocols.", type: "article" },
  "/blog/peptides-sleep-optimization": { title: "Peptides for Sleep Optimization: DSIP and Beyond", desc: "Guide to sleep-optimizing peptides including DSIP, pinealon, and the N-259 sleep protocol.", type: "article" },
  "/blog/future-peptide-therapy": { title: "The Future of Peptide Therapy: Emerging Trends", desc: "Emerging trends in peptide therapy including new compounds, delivery methods, and regulatory developments.", type: "article" },
  "/blog/peptide-practice-business": { title: "Building a Peptide Therapy Business: Practice Guide", desc: "Business strategies for building and growing a successful peptide therapy practice.", type: "article" },
  "/blog/reconstitution-guide": { title: "Peptide Reconstitution Guide: Step-by-Step Instructions", desc: "Detailed reconstitution guide with bacteriostatic water calculations, storage tips, and common mistakes to avoid.", type: "article" },
  "/blog/503a-vs-503b": { title: "503A vs 503B Pharmacies: Understanding Compounding Regulations", desc: "Comprehensive comparison of 503A and 503B pharmacy regulations for peptide compounding.", type: "article" },
  "/blog/fda-peptide-regulations-2026": { title: "FDA Peptide Regulations 2026: What Providers Need to Know", desc: "Updated guide to FDA peptide regulations in 2026 including 503A bulks list changes and enforcement actions.", type: "article" },
  "/blog/peptides-gut-health": { title: "Peptides for Gut Health: BPC-157, KPV and Larazotide", desc: "Clinical guide to gut-healing peptides including BPC-157, KPV, and larazotide for GI conditions.", type: "article" },
  "/blog/n-259-sleep-science": { title: "The Science of Superior Sleep: Deconstructing the N-259 Protocol", desc: "How Apigenin, Magnesium Glycinate, L-Theanine, and physiological melatonin work synergistically for optimal sleep.", type: "article" },
  "/blog/n-259-beyond-melatonin": { title: "Beyond Melatonin: Why Your Sleep Protocol is Missing 3 Key Ingredients", desc: "Understanding the multi-pathway approach to sleep: GABA support, neuromuscular relaxation, and alpha-wave promotion.", type: "article" },
  "/blog/n-69-neuroscience-desire": { title: "The Neuroscience of Desire: How N-69 Reboots the Brain-Body Connection", desc: "A deep dive into the 5-pathway approach of NALT, Kisspeptin, PT-141, Oxytocin, and VIP for sexual wellness.", type: "article" },
  "/blog/n-69-brain-libido": { title: "Is Your Brain the Reason You Are Not in the Mood?", desc: "How stress, dopamine depletion, and hormonal imbalances affect desire, and the science of restoring it.", type: "article" },
  "/blog/n-111-holy-trinity": { title: "The Holy Trinity of Nootropics: Why N-111 is a Game-Changer", desc: "How J147, Dihexa, and Noopept work together for neurogenesis, memory enhancement, and neuroprotection.", type: "article" },
  "/blog/n-111-neurogenesis": { title: "Are You Building a Better Brain, or Just Renting It?", desc: "Why true cognitive enhancement requires growing new neurons and synapses, not just temporary stimulation.", type: "article" },
  "/blog/n-5550-brain-body": { title: "The Ultimate Brain-Body Upgrade: How N-5550 Tackles Cognition and Metabolism", desc: "Dihexa, Tesofensine, and Methylene Blue for addressing brain fog and metabolic dysfunction together.", type: "article" },
  "/blog/n-5550-brain-fat": { title: "The Brain-Fat Connection: Why Your Weight Loss Stall is All in Your Head", desc: "How dopamine depletion and brain chemistry affect appetite, metabolism, and weight loss resistance.", type: "article" },
  "/blog/n-2331-cognitive-stack": { title: "The Ultimate Cognitive Enhancement Stack: Deconstructing N-2331", desc: "How Dihexa, Selank, Semax, and NAD+ work synergistically for comprehensive brain optimization.", type: "article" },
  "/blog/n-2331-anxiety-cognition": { title: "The Anxiety-Cognition Connection: Stress and Mental Performance", desc: "How chronic stress impairs cognitive function and the science of restoring mental clarity.", type: "article" },
  "/blog/rg-5555-healing-cascade": { title: "The 4-Step Cascade of Superior Healing: Deconstructing RG-5555", desc: "How BPC-157, TB-500, KPV, and Larazotide work together for comprehensive injury recovery.", type: "article" },
  "/blog/rg-5555-gut-healing": { title: "Is Your Gut Sabotaging Your Injury Recovery?", desc: "How gut permeability affects systemic inflammation and the role of Larazotide in healing.", type: "article" },
  "/blog/m-51-push-pull": { title: "The Push-Pull Effect: How M-51 Burns Fat from Two Directions", desc: "How 5-Amino-1MQ and SLU-PP-332 work synergistically to inhibit fat storage and activate fat burning.", type: "article" },
  "/blog/m-51-nnmt": { title: "The Hidden Enzyme Keeping You Fat: Understanding NNMT", desc: "How NNMT inhibition with 5-Amino-1MQ can unlock stubborn fat loss and improve metabolic health.", type: "article" },
  "/blog/m-2531-cellular-engines": { title: "The Signal and the Fuel: How M-2531 Rejuvenates Cellular Engines", desc: "How MOTS-c, NAD+, and mitochondrial support compounds restore cellular energy production.", type: "article" },
  "/blog/m-2531-exercise-paradox": { title: "The Exercise Paradox: Working Out But Still Feeling Old?", desc: "Why exercise alone is not enough and how mitochondrial peptides can restore youthful energy.", type: "article" },
  "/blog/w-1175-exercise-pill": { title: "The Exercise in a Pill Phenomenon: Deconstructing W-1175", desc: "How SLU-PP-332 and Orforglipron combine exercise mimetics with GLP-1 for metabolic optimization.", type: "article" },
'''

# Insert before the consent forms section
target = '  "/resources/consent-forms":'
if target in content:
    content = content.replace(target, new_entries + '\n' + target)
    with open('scripts/generate-seo-pages.cjs', 'w') as f:
        f.write(content)
    print("SUCCESS: Added all missing entries")
else:
    print(f"ERROR: Could not find insertion point: {target}")
